This notebook does concatenates the json data files into a single dataframe which is then exported to the folder /processed as a CSV. Before export it checks it for missing values, to decide which columns to drop and organises the data.

In [ ]:
import pandas as pd
from datetime import datetime, timedelta
from pathlib import Path
import math
import json

In [2]:
dir_processed = Path('../data/processed')
dir_processed.mkdir(exist_ok=True)
dir_raw = Path('../data/raw')
dir_raw.mkdir(exist_ok=True)

In [3]:
def load_json(file):

    with open(file, "r") as f:
        data_raw = json.load(f)

    return pd.DataFrame(data_raw['data'])

In [4]:
c = 0 
full_dataset = []

for file in sorted(dir_raw.glob("*.json")):
    imported_data = load_json(file)

    full_dataset.append(imported_data)

dataset = pd.concat(full_dataset, ignore_index=True)

In [5]:
dataset['date'] = pd.to_datetime(dataset['event_date'])
type(dataset['date'][1])

pandas.Timestamp

In [ ]:
"try to see what is in the data by printing the below functions"

type(dataset)
type(dataset['event_date'])
type(dataset['date'][1])
dataset

,event_id_cnty,event_date,time_precision,disorder_type,event_type,sub_event_type,actor1,assoc_actor_1,inter1,actor2,...,civilian_targeting,country,admin1,admin3,location,geo_precision,source,fatalities,tags,date
0,SYR137497,2024-12-13,1,Political violence,Violence against civilians,Abduction/forced disappearance,QSD: Syrian Democratic Forces,,Rebel group,Civilians (Syria),...,Civilian targeting,Syria,Ar Raqqa,Ar Raqqa,Ar-Raqqa - Unspecified,1,Alkhabour,0,,2024-12-13
1,SYR137503,2024-12-08,1,Political violence,Explosions/Remote violence,Air/drone strike,Military Forces of Israel (2022-),,External/Other forces,Military Forces of Syria (2000-2024),...,,Syria,Deir ez Zor,Abu Kamal,Al-Bukamal - Unspecified,2,SOHR,0,,2024-12-08
2,SYR137504,2024-12-08,1,Political violence,Explosions/Remote violence,Air/drone strike,Military Forces of Israel (2022-),,External/Other forces,Military Forces of Syria (2000-2024),...,,Syria,Deir ez Zor,Tabni,Manjm Al-Malah salt mine,1,SOHR,0,,2024-12-08
3,SYR137508,2024-12-08,1,Political violence,Explosions/Remote violence,Air/drone strike,Military Forces of Israel (2022-),,External/Other forces,Military Forces of Syria (2000-2024),...,,Syria,Rural Damascus,Qatana,Qatana,2,Halab Today; SOHR,0,,2024-12-08
4,SYR137509,2024-12-08,1,Political violence,Explosions/Remote violence,Air/drone strike,Military Forces of Israel (2022-),,External/Other forces,Military Forces of Syria (2000-2024),...,,Syria,Dara,As Sanamayn,As-Sanamayn,2,SHAAM,0,,2024-12-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16840,SYR155155,2026-07-17,1,Political violence,Explosions/Remote violence,Remote explosive/landmine/IED,Unidentified Armed Group (Syria),,Political militia,Civilians (Syria),...,Civilian targeting,Syria,Rural Damascus,Dhameer,Dhameer,1,Halab Today; SHAAM; SOHR; Syria TV,1,Terrorist activity,2026-07-17
16841,SYR155156,2026-07-16,1,Political violence,Explosions/Remote violence,Shelling/artillery/missile attack,Military Forces of Israel (2022-),,External/Other forces,,...,,Syria,Dara,Ash Shajara,Maariya,1,Alkhabour; SOHR; Syria TV,0,Foreign military engagement,2026-07-16
16842,SYR155157,2026-07-14,1,Strategic developments,Strategic developments,Other,Civilians (Syria),,Civilians,,...,,Syria,Dara,Ash Shajara,Maariya,1,Halab Today; Sijil; Syria TV,0,,2026-07-14
16843,SYR155158,2026-07-17,1,Demonstrations,Riots,Violent demonstration,Rioters (Syria),,Rioters,,...,,Syria,Dara,Dara,Nasib,1,Dar'a 24; SOHR,0,,2026-07-17
16844,SYR155159,2026-07-14,1,Strategic developments,Strategic developments,Other,Settlers (Israel),,Political militia,Military Forces of Israel (2022-),...,,Syria,Quneitra,Masaada,Ghajar,2,Times of Israel,0,Foreign military engagement,2026-07-14

In [7]:
dataset = dataset.sort_values(by='date')
dataset.head(10)

,event_id_cnty,event_date,time_precision,disorder_type,event_type,sub_event_type,actor1,assoc_actor_1,inter1,actor2,...,civilian_targeting,country,admin1,admin3,location,geo_precision,source,fatalities,tags,date
15736,SYR154018,2024-12-08,1,Strategic developments,Strategic developments,Non-violent transfer of territory,Military Operations Command,,Rebel group,Military Forces of Syria (2000-2024),...,,Syria,Rural Damascus,Bait Jan,Bait Jan,2,Syrian Memory Project,0,,2024-12-08
15734,SYR154016,2024-12-08,1,Strategic developments,Strategic developments,Non-violent transfer of territory,Military Operations Command,,Rebel group,Military Forces of Syria (2000-2024),...,,Syria,Rural Damascus,Nashabiyeh,Nashabiyeh,2,Syrian Memory Project,0,,2024-12-08
15735,SYR154017,2024-12-08,1,Strategic developments,Strategic developments,Non-violent transfer of territory,JSH: Free Syrian Army,,Rebel group,Military Forces of Syria (2000-2024),...,,Syria,Rural Damascus,Sabe Byar,Sabe Byar,2,Syrian Memory Project,0,,2024-12-08
15737,SYR154019,2024-12-08,1,Strategic developments,Strategic developments,Non-violent transfer of territory,Damascus Liberation Operations Room,,Rebel group,Military Forces of Syria (2000-2024),...,,Syria,Rural Damascus,Qatana,Qatana,2,Syrian Memory Project,0,,2024-12-08
1377,SYR137757,2024-12-08,1,Strategic developments,Strategic developments,Non-violent transfer of territory,Military Operations Command,,Rebel group,Military Forces of Syria (2000-2024),...,,Syria,Homs,Sokhneh,Sokhneh,2,Halab Today; Telegram,0,,2024-12-08
1376,SYR137637,2024-12-08,2,Political violence,Violence against civilians,Abduction/forced disappearance,Military Forces of Israel (2022-),,External/Other forces,Civilians (Syria),...,Civilian targeting,Syria,Quneitra,Masaada,Masaada,2,SOHR,0,,2024-12-08
15738,SYR154020,2024-12-08,1,Strategic developments,Strategic developments,Non-violent transfer of territory,Military Operations Command,,Rebel group,Military Forces of Syria (2000-2024),...,,Syria,Rural Damascus,Arbin,Arbin,2,Syrian Memory Project,0,,2024-12-08
15733,SYR154015,2024-12-08,1,Strategic developments,Strategic developments,Non-violent transfer of territory,Military Operations Command,,Rebel group,Military Forces of Syria (2000-2024),...,,Syria,Rural Damascus,Harasta,Harasta,2,Syrian Memory Project,0,,2024-12-08
15739,SYR154021,2024-12-08,1,Strategic developments,Strategic developments,Non-violent transfer of territory,Military Operations Command,,Rebel group,Military Forces of Syria (2000-2024),...,,Syria,Rural Damascus,Babella,Babella,2,Syrian Memory Project,0,,2024-12-08
15741,SYR154023,2024-12-08,1,Strategic developments,Strategic developments,Non-violent transfer of territory,Military Operations Command,,Rebel group,Military Forces of Syria (2000-2024),...,,Syria,Rural Damascus,Kafr Batna,Kafr Batna,2,Syrian Memory Project,0,,2024-12-08

In [ ]:
"function to reset index in case that becomes necessary"

def df_index(dataframe):
    rows = len(dataframe)

    dataframe.index = range(1, rows+1)
    
    return dataframe

dataset = df_index(dataset)

In [9]:
"from lecture W03D02: missing values appear as an empty string so isna() and isnul() doesn't work"

def missing_values(column_name):
    sum_nas = float((dataset[column_name] == '').sum())
    ratio_nas = round(float((dataset[column_name] == '').sum() / len(dataset)), 2)
    return {f"column": {column_name}, "sum": sum_nas, "ratio": ratio_nas}

In [ ]:
"test function with one column"

missing_values('inter1')

{'column': {'inter1'}, 'sum': 0.0, 'ratio': 0.0}

In [ ]:
"finding the column names to perform the same test on all columns"

columns = dataset.keys()

print(columns)

Index(['event_id_cnty', 'event_date', 'time_precision', 'disorder_type',
       'event_type', 'sub_event_type', 'actor1', 'assoc_actor_1', 'inter1',
       'actor2', 'assoc_actor_2', 'inter2', 'civilian_targeting', 'country',
       'admin1', 'admin3', 'location', 'geo_precision', 'source', 'fatalities',
       'tags', 'date'],
      dtype='str')

In [12]:
"copying column names over the columns variable"

columns = ['event_id_cnty', 'event_date', 'time_precision', 'disorder_type',
       'event_type', 'sub_event_type', 'actor1', 'assoc_actor_1', 'inter1',
       'actor2', 'assoc_actor_2', 'inter2', 'civilian_targeting', 'country',
       'admin1', 'admin3', 'location', 'geo_precision', 'source', 'fatalities',
       'tags']

In [13]:
all_missing_values = []

for column in columns:
    print(f"column: {column}")
    missing_value = missing_values(column)
    if missing_value['sum'] > 0:
        all_missing_values.append(missing_value)

    # print(f"missing values: {missing_value}")
    # dict_missing_values[column] = missing_value

column: event_id_cnty
column: event_date
column: time_precision
column: disorder_type
column: event_type
column: sub_event_type
column: actor1
column: assoc_actor_1
column: inter1
column: actor2
column: assoc_actor_2
column: inter2
column: civilian_targeting
column: country
column: admin1
column: admin3
column: location
column: geo_precision
column: source
column: fatalities
column: tags

In [14]:
len(all_missing_values)
all_missing_values

[{'column': {'assoc_actor_1'}, 'sum': 14198.0, 'ratio': 0.84},
 {'column': {'actor2'}, 'sum': 5356.0, 'ratio': 0.32},
 {'column': {'assoc_actor_2'}, 'sum': 13603.0, 'ratio': 0.81},
 {'column': {'inter2'}, 'sum': 5356.0, 'ratio': 0.32},
 {'column': {'civilian_targeting'}, 'sum': 11645.0, 'ratio': 0.69},
 {'column': {'tags'}, 'sum': 14138.0, 'ratio': 0.84}]

In [15]:
"optional, manual tests to see if other columns contain missing values coded as n/a or null"

dataset['admin3'].isna().all()
dataset['admin3'].isnull().all()

np.False_

In [16]:
"check whether there are duplicate values in dataset"

"duplicated() checks if the row is a duplicate of the former row"

duplicates = dataset[dataset.duplicated()]
duplicates

Empty DataFrame
Columns: [event_id_cnty, event_date, time_precision, disorder_type, event_type, sub_event_type, actor1, assoc_actor_1, inter1, actor2, assoc_actor_2, inter2, civilian_targeting, country, admin1, admin3, location, geo_precision, source, fatalities, tags, date]
Index: []

[0 rows x 22 columns]

None of the columns are dropped since they may become helpful in the analysis. The next section creates helper columns to estimate the time passed since the fall of the Assad regime - 08 Dec 2024 (inclusive).

In [ ]:
"read the dataset back into python if restarting - keep green if not"

# dataset = pd.read_csv(dir_processed / 'dataset.csv')
# dataset.index = dataset.index + 1
# dataset

In [17]:
"setting up parameters to create helper column 'interval', measuring months elapsed since the regime fall"

transfer_date = pd.to_datetime('2024-12-08')
reference_date = pd.to_datetime('2024-12-07')
month = timedelta(days=31)
one_day = timedelta(days=1)

dataset['interval'] = (dataset['date'] - transfer_date).floordiv(month, fill_value=0)

In [18]:
"isin() checks where there are potential missing values in newly created helper column"

value = ['NA']
dataset[dataset['interval'].isin(value)]

Empty DataFrame
Columns: [event_id_cnty, event_date, time_precision, disorder_type, event_type, sub_event_type, actor1, assoc_actor_1, inter1, actor2, assoc_actor_2, inter2, civilian_targeting, country, admin1, admin3, location, geo_precision, source, fatalities, tags, date, interval]
Index: []

[0 rows x 23 columns]

In [20]:
dataset['start date'] = (transfer_date + dataset['interval'] * month)

In [21]:
dataset['end date'] = (dataset['start date'] + month - one_day)

dataset.columns.tolist()

['event_id_cnty',
 'event_date',
 'time_precision',
 'disorder_type',
 'event_type',
 'sub_event_type',
 'actor1',
 'assoc_actor_1',
 'inter1',
 'actor2',
 'assoc_actor_2',
 'inter2',
 'civilian_targeting',
 'country',
 'admin1',
 'admin3',
 'location',
 'geo_precision',
 'source',
 'fatalities',
 'tags',
 'date',
 'interval',
 'start date',
 'end date']

In [22]:
"check boundaries of individual intervals and whether they match event date" 
"by looking at head and tail ends of returned df"

dataset[dataset['interval'] == 18]

,event_id_cnty,event_date,time_precision,disorder_type,event_type,sub_event_type,actor1,assoc_actor_1,inter1,actor2,...,admin3,location,geo_precision,source,fatalities,tags,date,interval,start date,end date
16284,SYR154497,2026-06-19,1,Political violence,Battles,Armed clash,Al Tokan Tribal Militia (Syria),,Identity militia,Al Tokan Tribal Militia (Syria),...,Suran,Khafsine,1,SOHR,0,,2026-06-19,18,2026-06-19,2026-07-19
16285,SYR154567,2026-06-19,1,Strategic developments,Strategic developments,Other,Protesters (Syria),Teachers (Syria),Protesters,,...,Ghabagheb,Ghabagheb,1,SOHR,0,,2026-06-19,18,2026-06-19,2026-07-19
16286,SYR154480,2026-06-19,1,Political violence,Explosions/Remote violence,Air/drone strike,Global Coalition Against Daesh,,External/Other forces,Civilians (Syria),...,Daret Azza,Jabal Al Sheikh Barakat,2,Syria TV,0,,2026-06-19,18,2026-06-19,2026-07-19
16287,SYR154475,2026-06-19,1,Political violence,Violence against civilians,Abduction/forced disappearance,Military Forces of Israel (2022-),,External/Other forces,Civilians (Syria),...,Ash Shajara,Al Aarada,2,Sijil; SOHR,0,,2026-06-19,18,2026-06-19,2026-07-19
16288,SYR154481,2026-06-19,1,Political violence,Explosions/Remote violence,Air/drone strike,Global Coalition Against Daesh,Military Forces of the United States (2025-),External/Other forces,Islamic State in Iraq and the Levant (ISIL),...,Dana,Mashhad Ruhin,2,Alkhabour; Halab Today; North Press Agency; SO...,1,,2026-06-19,18,2026-06-19,2026-07-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16841,SYR155097,2026-07-17,1,Political violence,Battles,Armed clash,Al Sabinah Al Kubra Communal Militia (Syria),,Identity militia,Al Sabinah Al Kubra Communal Militia (Syria),...,Babella,Al Sabinah Al Kubra,1,SOHR,1,,2026-07-17,18,2026-06-19,2026-07-19
16842,SYR155124,2026-07-17,1,Strategic developments,Strategic developments,Change to group/activity,Military Forces of Israel (2022-),,External/Other forces,,...,Ash Shajara,Abdin,1,Dar'a 24; Halab Today; North Press Agency; SHA...,0,Foreign military engagement,2026-07-17,18,2026-06-19,2026-07-19
16843,SYR155125,2026-07-17,1,Strategic developments,Strategic developments,Change to group/activity,Military Forces of Israel (2022-),,External/Other forces,,...,Quneitra,Rweheineh,1,Dar'a 24; Sijil; SOHR,0,Foreign military engagement,2026-07-17,18,2026-06-19,2026-07-19
16844,SYR155109,2026-07-17,1,Strategic developments,Strategic developments,Arrests,Police Forces of Syria (2024-),,State forces,Smugglers (Syria),...,Homs,Homs - Unspecified,3,North Press Agency; SY24; Syria TV,0,,2026-07-17,18,2026-06-19,2026-07-19
16845,SYR155089,2026-07-17,1,Political violence,Battles,Armed clash,Al Damalkha Tribal Militia (Syria),,Identity militia,Al Damalkha Tribal Militia (Syria),...,Menbij,Kherbet Al Shiyab,1,SOHR,1,,2026-07-17,18,2026-06-19,2026-07-19

In [28]:
dataset.to_csv(dir_processed/"dataset.csv", index=False)