This notebook focussed on a geographic analysis of the conflict categories

In [ ]:
import pandas as pd
from pathlib import Path
import plotly.express as px
import plotly.graph_objects as go

In [2]:
dir_processed = Path('../data/processed')
dir_processed.mkdir(exist_ok=True)
dir_raw = Path('../data/raw')
dir_raw.mkdir(exist_ok=True)

In [3]:
"function resets index if new dataframes returns jumbled indexes"

def df_index(dataframe):
    rows = len(dataframe)

    dataframe.index = range(1, rows+1)
    
    return dataframe

In [4]:
dataset = pd.read_csv(dir_processed / 'dataset.csv')
dataset.index = dataset.index + 1
dataset.head(20)

,event_id_cnty,event_date,time_precision,disorder_type,event_type,sub_event_type,actor1,assoc_actor_1,inter1,actor2,...,admin3,location,geo_precision,source,fatalities,tags,date,interval,start date,end date
1,SYR154018,2024-12-08,1,Strategic developments,Strategic developments,Non-violent transfer of territory,Military Operations Command,NaN,Rebel group,Military Forces of Syria (2000-2024),...,Bait Jan,Bait Jan,2,Syrian Memory Project,0,NaN,2024-12-08,0,2024-12-08,2025-01-07
2,SYR154016,2024-12-08,1,Strategic developments,Strategic developments,Non-violent transfer of territory,Military Operations Command,NaN,Rebel group,Military Forces of Syria (2000-2024),...,Nashabiyeh,Nashabiyeh,2,Syrian Memory Project,0,NaN,2024-12-08,0,2024-12-08,2025-01-07
3,SYR154017,2024-12-08,1,Strategic developments,Strategic developments,Non-violent transfer of territory,JSH: Free Syrian Army,NaN,Rebel group,Military Forces of Syria (2000-2024),...,Sabe Byar,Sabe Byar,2,Syrian Memory Project,0,NaN,2024-12-08,0,2024-12-08,2025-01-07
4,SYR154019,2024-12-08,1,Strategic developments,Strategic developments,Non-violent transfer of territory,Damascus Liberation Operations Room,NaN,Rebel group,Military Forces of Syria (2000-2024),...,Qatana,Qatana,2,Syrian Memory Project,0,NaN,2024-12-08,0,2024-12-08,2025-01-07
5,SYR137757,2024-12-08,1,Strategic developments,Strategic developments,Non-violent transfer of territory,Military Operations Command,NaN,Rebel group,Military Forces of Syria (2000-2024),...,Sokhneh,Sokhneh,2,Halab Today; Telegram,0,NaN,2024-12-08,0,2024-12-08,2025-01-07
6,SYR137637,2024-12-08,2,Political violence,Violence against civilians,Abduction/forced disappearance,Military Forces of Israel (2022-),NaN,External/Other forces,Civilians (Syria),...,Masaada,Masaada,2,SOHR,0,NaN,2024-12-08,0,2024-12-08,2025-01-07
7,SYR154020,2024-12-08,1,Strategic developments,Strategic developments,Non-violent transfer of territory,Military Operations Command,NaN,Rebel group,Military Forces of Syria (2000-2024),...,Arbin,Arbin,2,Syrian Memory Project,0,NaN,2024-12-08,0,2024-12-08,2025-01-07
8,SYR154015,2024-12-08,1,Strategic developments,Strategic developments,Non-violent transfer of territory,Military Operations Command,NaN,Rebel group,Military Forces of Syria (2000-2024),...,Harasta,Harasta,2,Syrian Memory Project,0,NaN,2024-12-08,0,2024-12-08,2025-01-07
9,SYR154021,2024-12-08,1,Strategic developments,Strategic developments,Non-violent transfer of territory,Military Operations Command,NaN,Rebel group,Military Forces of Syria (2000-2024),...,Babella,Babella,2,Syrian Memory Project,0,NaN,2024-12-08,0,2024-12-08,2025-01-07
10,SYR154023,2024-12-08,1,Strategic developments,Strategic developments,Non-violent transfer of territory,Military Operations Command,NaN,Rebel group,Military Forces of Syria (2000-2024),...,Kafr Batna,Kafr Batna,2,Syrian Memory Project,0,NaN,2024-12-08,0,2024-12-08,2025-01-07
11,SYR154024,2024-12-08,1,Strategic developments,Strategic developments,Non-violent transfer of territory,Military Operations Command,NaN,Rebel group,Military Forces of Syria (2000-2024),...,Maliha,Maliha,2,Syrian Memory Project,0,NaN,2024-12-08,0,2024-12-08,2025-01-07
12,SYR154025,2024-12-08,1,Strategic developments,Strategic developments,Non-violent transfer of territory,Military Operations Command,NaN,Rebel group,Military Forces of Syria (2000-2024),...,Qudsiya,Qodsayya,2,Syrian Memory Project,0,NaN,2024-12-08,0,2024-12-08,2025-01-07
13,SYR154026,2024-12-08,1,Strategic developments,Strategic developments,Non-violent transfer of territory,Military Operations Command,NaN,Rebel group,Military Forces of Syria (2000-2024),...,Esal El Ward,Assal al Ward,2,Syrian Memory Project,0,NaN,2024-12-08,0,2024-12-08,2025-01-07
14,SYR154027,2024-12-08,1,Strategic developments,Strategic developments,Non-violent transfer of territory,Military Operations Command,NaN,Rebel group,Military Forces of Syria (2000-2024),...,Jeb Ej Jarrah,Jeb Ej-Jarrah,2,Syrian Memory Project,0,NaN,2024-12-08,0,2024-12-08,2025-01-07
15,SYR154028,2024-12-08,1,Strategic developments,Strategic developments,Non-violent transfer of territory,Military Operations Command,NaN,Rebel group,Military Forces of Syria (2000-2024),...,Farqalas,Farqalas,2,Syrian Memory Project,0,NaN,2024-12-08,0,2024-12-08,2025-01-07
16,SYR154022,2024-12-08,1,Strategic developments,Strategic developments,Non-violent transfer of territory,Military Operations Command,NaN,Rebel group,Military Forces of Syria (2000-2024),...,Jaramana,Jaramana,2,Syrian Memory Project,0,NaN,2024-12-08,0,2024-12-08,2025-01-07
17,SYR154014,2024-12-08,1,Strategic developments,Strategic developments,Non-violent transfer of territory,Military Operations Command,NaN,Rebel group,Military Forces of Syria (2000-2024),...,Haran Alawameed,Haran Alawameed,2,Syrian Memory Project,0,NaN,2024-12-08,0,2024-12-08,2025-01-07
18,SYR154013,2024-12-08,1,Strategic developments,Strategic developments,Non-violent transfer of territory,Military Operations Command,NaN,Rebel group,Military Forces of Syria (2000-2024),...,Ghizlaniyyeh,Ghizlaniyyeh,2,Syrian Memory Project,0,NaN,2024-12-08,0,2024-12-08,2025-01-07
19,SYR154012,2024-12-08,1,Strategic developments,Strategic developments,Non-violent transfer of territory,Military Operations Command,NaN,Rebel group,Military Forces of Syria (2000-2024),...,Duma,Duma,2,Syrian Memory Project,0,NaN,2024-12-08,0,2024-12-08,2025-01-07
20,SYR153999,2024-12-08,1,Strategic developments,Strategic developments,Non-violent transfer of territory,Military Operations Command,NaN,Rebel group,Military Forces of Syria (2000-2024),...,Jirud,Jirud,2,Syrian Memory Project,0,NaN,2024-12-08,0,2024-12-08,2025-01-07

In [5]:
dataset_dates = pd.read_csv(dir_processed / 'dataset_dates.csv')
dataset_dates

    interval  start date    end date
0          0  2024-12-08  2025-01-07
1          1  2025-01-08  2025-02-07
2          2  2025-02-08  2025-03-10
3          3  2025-03-11  2025-04-10
4          4  2025-04-11  2025-05-11
5          5  2025-05-12  2025-06-11
6          6  2025-06-12  2025-07-12
7          7  2025-07-13  2025-08-12
8          8  2025-08-13  2025-09-12
9          9  2025-09-13  2025-10-13
10        10  2025-10-14  2025-11-13
11        11  2025-11-14  2025-12-14
12        12  2025-12-15  2026-01-14
13        13  2026-01-15  2026-02-14
14        14  2026-02-15  2026-03-17
15        15  2026-03-18  2026-04-17
16        16  2026-04-18  2026-05-18
17        17  2026-05-19  2026-06-18
18        18  2026-06-19  2026-07-19

In [6]:
def color_map_grey(category):
    colors = [
        "#C5CDD5", 
        "#C4CCD0", 
        "#D0CBC2",
        "#CBCBCB", 
        "#B8B8B8",
        "#C8C1B6", 
        "#C1C1C1", 
        "#A9A9A9", 
        "#B6AE9E",
        "#B0BAC5", 
        "#BBC3CD", 
        "#ACACAC", 
        "#909EAE", 
        "#B5BEC9", 
        "#808080", 
        "#6082B6", 
        "#4F4F4F",
        "#A49A87",
        "#87A0A4",
        "#C8CCD5"
        ] 
    return {event: colors[i] for i, event in enumerate(category)}

In [7]:
"refactored return statement after Lecture W03D04"

def color_map_pop(selected_category, category_list):
    return {event: "#5C8DC5" if category_list[i] == selected_category else "#D3D3D3" for i, event in enumerate(category_list)}

In [ ]:
"refactored return statement after Lecture W03D04"

def color_map_pop_multiple(selected_categories, category_list):
        return {admin: "#5C8DC5" if admin in selected_categories else "#D3D3D3" for i, admin in enumerate(category_list)}

In [ ]:
dataset_geo = (
    dataset
    .groupby(['admin1'], as_index=False)['event_type']
    .size()
)

df_index(dataset_geo)

dataset_geo.head(30)

            admin1  size
1       Al Hasakeh  1926
2           Aleppo  2667
3         Ar Raqqa  1259
4        As Sweida  1065
5         Damascus   471
6             Dara  1305
7      Deir ez Zor  2389
8             Hama   744
9             Homs  1163
10           Idleb   420
11        Lattakia   737
12        Quneitra  1515
13  Rural Damascus   816
14         Tartous   368

In [10]:
geo_admin1 = list(dataset_geo['admin1'].unique())
geo_admin1

['Al Hasakeh',
 'Aleppo',
 'Ar Raqqa',
 'As Sweida',
 'Damascus',
 'Dara',
 'Deir ez Zor',
 'Hama',
 'Homs',
 'Idleb',
 'Lattakia',
 'Quneitra',
 'Rural Damascus',
 'Tartous']

In [11]:
govs = ['Al Hasakeh', 'Aleppo', 'Deir ez Zor']

In [12]:
bar_geo = px.bar(
    dataset_geo,
    x='admin1',
    y='size',
    color_discrete_map=color_map_grey(geo_admin1),
    labels = {'admin1': 'Governorates', 'event_count': 'Number of events'},
)

bar_geo.update_layout(
    title = 'Geographic distribution of conflict events since the fall of the Assad regime',
    title_font_size = 14,
    font_size=10,
    yaxis= dict(tickvals = [0, 400, 800, 1200, 1600, 2000, 2400, 2800])
)

bar_geo.update_traces(marker_color='rgb(211,211,211)')

In [13]:
bar_geo.write_html("../docs/assets/bar_governorates.html")

In [ ]:
dataset_geo_by_interval = (
    dataset
    .groupby(['interval', 'admin1'], as_index=False)['event_type']
    .size()
)

df_index(dataset_geo_by_interval)

dataset_geo_by_interval.head(10)

In [ ]:
df_sd = (
    dataset
    .query("event_type == 'Strategic developments'")
    .groupby(['interval', 'admin1', 'sub_event_type'], as_index=False)
    .agg(event_count=('sub_event_type', 'size'))
)
df_sd.head(10)

In [18]:
bar_sd_geo = px.bar(
    dataset_geo_by_interval, 
    x='interval',
    y='size',
    color='admin1',
    color_discrete_map=color_map_grey(geo_admin1),
)

bar_sd_geo.update_layout(
    title = 'Geographic distribution of conflict events since the fall of the Assad regime',
    title_font_size = 14,
    font_size=10
    # yaxis= dict(tickvals = [0, 400, 800, 1200, 1600, 2000, 2400, 2800])
)

In [20]:
bubble_geo_events = px.scatter(
    dataset_geo_by_interval, 
    x="interval", 
    y="size",
    size="size", 
    color="admin1",
    hover_name="admin1", 
    size_max=20, 
    color_discrete_map=color_map_grey(geo_admin1), 
    labels={'interval':"Months elapsed since 08/12/2024", 'size':"Number of events"})

bubble_geo_events.update_xaxes(dtick=1)

bubble_geo_events.update_layout(
    title = 'Timeline of conflict events by governorates',
    legend_title_text = "Governorates",
    title_font_size = 14,
    font_size=10    
)

In [21]:
bubble_geo_events.write_html("../docs/assets/bubble_events_admin1_interval.html")

Sub-section: Line charts representing events occurrence per governorate since the regime collapse

In [33]:
df_sd_counts_only = (
    dataset
    .query("event_type == 'Strategic developments'")
    .groupby(['interval', 'admin1'], as_index=False)['sub_event_type']
    .size()
)

df_sd_counts_only.head(10)

line_sd = px.line(
    df_sd_counts_only, 
    x="interval", 
    y="size", 
    color='admin1',
    color_discrete_map=color_map_grey(geo_admin1)
)

line_sd.update_xaxes(dtick=1)

line_sd

repeat the analysis but this time keep only the governorates with the highest number of occurrences

In [34]:
df_sd_selected = (
    df_sd_counts_only
    .query("admin1 in ['Aleppo', 'Quneitra', 'Al Hasakeh', 'Deir ez Zor']")
)
df_sd_selected.head(10)

    interval       admin1  size
0          0   Al Hasakeh    37
1          0       Aleppo    31
6          0  Deir ez Zor    38
10         0     Quneitra    35
13         1   Al Hasakeh    39
14         1       Aleppo    15
19         1  Deir ez Zor    37
24         1     Quneitra    19
27         2   Al Hasakeh    35
28         2       Aleppo    22

In [37]:
line_sd_selected_admin = px.line(
    df_sd_selected, 
    x="interval", 
    y="size", 
    color='admin1',
    color_discrete_map=color_map_grey(list(df_sd_selected['admin1'].unique())),
    labels={'size':'Number of events', "interval": "Months elapsed since 08/12/2024"}
)

line_sd_selected_admin.update_layout(
    title = 'Timeline of strategic developments in most affected governorates',
    legend_title_text = "Governorates",
    title_font_size = 14,
    font_size=10    
)

line_sd_selected_admin.update_xaxes(dtick=1)

In [38]:
line_sd_selected_admin.write_html("../docs/assets/line_sd.html")

In [41]:
df_sd_tt = (
    df_sd
    .query("sub_event_type == 'Non-violent transfer of territory'")
)
df_sd_tt.head(20)

     interval          admin1                     sub_event_type  event_count
3           0      Al Hasakeh  Non-violent transfer of territory            1
10          0          Aleppo  Non-violent transfer of territory            2
15          0        Ar Raqqa  Non-violent transfer of territory            2
21          0        Damascus  Non-violent transfer of territory            1
26          0            Dara  Non-violent transfer of territory            2
30          0     Deir ez Zor  Non-violent transfer of territory            8
35          0            Hama  Non-violent transfer of territory            9
39          0            Homs  Non-violent transfer of territory           17
44          0        Lattakia  Non-violent transfer of territory           22
49          0        Quneitra  Non-violent transfer of territory           11
54          0  Rural Damascus  Non-violent transfer of territory           32
58          0         Tartous  Non-violent transfer of territory           28
63          1      Al Hasakeh  Non-violent transfer of territory            1
211         4          Aleppo  Non-violent transfer of territory            1
327         6        Quneitra  Non-violent transfer of territory            1
619        13      Al Hasakeh  Non-violent transfer of territory           11
625        13          Aleppo  Non-violent transfer of territory           13
630        13        Ar Raqqa  Non-violent transfer of territory            3
647        13     Deir ez Zor  Non-violent transfer of territory            7
667        13  Rural Damascus  Non-violent transfer of territory            1

In [ ]:
df_sd_tt["interval"] = df_sd_tt["interval"].astype('string')

intervals_list = list(df_sd_tt['interval'].unique())

In [49]:
color_map_pop('13', intervals_list)

{'0': '#D3D3D3',
 '1': '#D3D3D3',
 '4': '#D3D3D3',
 '6': '#D3D3D3',
 '13': '#5C8DC5',
 '14': '#D3D3D3',
 '15': '#D3D3D3'}

In [ ]:

bar_sd_tt = px.bar(
    df_sd_tt, 
    x='admin1',
    y='event_count',
    color='interval',
    color_discrete_map=color_map_grey(intervals_list),
    category_orders = {'interval': ['13', '14', '15', '0', '1', '4', '6']},
    labels={'admin1':'Governorates', 'event_count': 'Number of events'}
    )

bar_sd_tt.update_layout(
    title = 'Non-violent transfer of territory by governorate and interval',
    title_font_size = 14,
    font_size=10
)

In [51]:
bar_sd_tt.write_html("../docs/assets/bar_non-violent_transfer_of_territory.html")

Geographic analysis of explosions/remote violence

In [52]:
df_erv = (
    dataset
    .query("event_type == 'Explosions/Remote violence'")
    .groupby(['interval', 'admin1'], as_index=False)['sub_event_type']
    .size()
)

df_erv.head(30)

    interval          admin1  size
0          0      Al Hasakeh   100
1          0          Aleppo   142
2          0        Ar Raqqa    61
3          0       As Sweida    14
4          0        Damascus    14
5          0            Dara    32
6          0     Deir ez Zor    59
7          0            Hama    22
8          0            Homs    16
9          0           Idleb    24
10         0        Lattakia    20
11         0        Quneitra     6
12         0  Rural Damascus    34
13         0         Tartous    11
14         1      Al Hasakeh    86
15         1          Aleppo   251
16         1        Ar Raqqa    85
17         1       As Sweida     7
18         1        Damascus     1
19         1            Dara    10
20         1     Deir ez Zor    50
21         1            Hama    23
22         1            Homs    17
23         1           Idleb    21
24         1        Lattakia    10
25         1        Quneitra     3
26         1  Rural Damascus     3
27         1         Tartous     1
28         2      Al Hasakeh    27
29         2          Aleppo   179

In [53]:
line_erv = px.line(
    df_erv, 
    x="interval", 
    y="size", 
    color='admin1',
    color_discrete_map=color_map_pop('Aleppo', geo_admin1),
    labels={"interval":"Months elapsed since 08/12/2024", "size":"Number of events"}
)

line_erv.update_layout(
    title = 'Timeline of explosions/remote violence across all governorates, Aleppo most affected in the immediate aftermath',
    legend_title_text = "Governorates",
    title_font_size = 14,
    font_size=10    
)

line_erv.update_xaxes(dtick=1)

In [156]:
line_erv.write_html("../docs/assets/line_erv.html")

Geographic analysis of violence against civilians

In [54]:
df_vac = (
    dataset
    .query("event_type == 'Violence against civilians'")
    .groupby(['interval', 'admin1'], as_index=False)['sub_event_type']
    .size()
)

df_vac.head(30)

    interval          admin1  size
0          0      Al Hasakeh    20
1          0          Aleppo    62
2          0        Ar Raqqa    32
3          0       As Sweida     6
4          0        Damascus     7
5          0            Dara    16
6          0     Deir ez Zor    21
7          0            Hama    25
8          0            Homs    34
9          0           Idleb     2
10         0        Lattakia    10
11         0        Quneitra     5
12         0  Rural Damascus     7
13         0         Tartous     9
14         1      Al Hasakeh    47
15         1          Aleppo    41
16         1        Ar Raqqa    34
17         1       As Sweida     5
18         1        Damascus     7
19         1            Dara    10
20         1     Deir ez Zor    52
21         1            Hama    33
22         1            Homs    70
23         1           Idleb     8
24         1        Lattakia     9
25         1        Quneitra     2
26         1  Rural Damascus    18
27         1         Tartous     6
28         2      Al Hasakeh    19
29         2          Aleppo    13

In [55]:
line_vac = px.line(
    df_vac, 
    x="interval", 
    y="size", 
    color='admin1',
    color_discrete_map=color_map_pop_multiple(['Al Hasakeh', 'Homs', 'Deir ez Zor', 'Aleppo'], geo_admin1),
    labels={"interval":"Months elapsed since 08/12/2024", "size":"Number of events"}
)

line_vac.update_layout(
    title = 'Timeline of violence against civilians across all governorates',
    legend_title_text = "Governorates",
    title_font_size = 14,
    font_size=10    
)

line_vac.update_xaxes(dtick=1)

In [236]:
line_vac.write_html("../docs/assets/line_vac.html")

In [ ]:
df_vac_afd = (
    dataset
    .query("sub_event_type == 'Abduction/forced disappearance'")
    .groupby(['interval', 'admin1'], as_index=False)['sub_event_type']
    .size()
)

In [60]:
df_vac_afd["interval"] = df_vac_afd["interval"].astype('string')

In [61]:
intervals_vac = list(df_vac_afd['interval'].unique())

In [ ]:

bar_vac_afd = px.bar(
    df_vac_afd, 
    x='admin1',
    y='size',
    color='interval',
    color_discrete_map=color_map_grey(intervals_vac),
    labels={'admin1':'Governorates', 'size': 'Number of events'}
    )

bar_vac_afd

bar_vac_afd.update_layout(
    title = 'Abductions/forced disappearances by governorate and interval',
    title_font_size = 14,
    font_size=10
)

In [ ]:

bubble_vac_afd = px.scatter(
    df_vac_afd, 
    x='admin1',
    y='size',
    size='size',
    color='interval',
    hover_name="interval",
    size_max=20, 
    color_discrete_map=color_map_pop_multiple(['0', '1', '13'], intervals_vac),
    labels={'admin1':'Governorates', 'size': 'Number of events'}
    )


bubble_vac_afd.update_layout(
    title = 'Abductions/forced disappearances by governorate and interval',
    title_font_size = 14,
    font_size=8
)

In [277]:
bubble_vac_afd.write_html("../docs/assets/bubble_vac_afd.html")